name: Dependency Submission

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:

  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - uses: gradle/actions/dependency-submission@v4
        with:
          dependency-graph-exclude-configurations: '.*[Tt]est(Compile|Runtime)Classpath'

  dependency-review:
    runs-on: ubuntu-latest
    needs: dependency-submission
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        if: ${{ startsWith(github.ref, 'refs/pull') }}
        with:
          comment-summary-in-pr: always